version: '3.9'

services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /Users/sibyl/vagrant-lamp-cluster/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - master_server
      - slave_server

  master_server:
    build: ./master
    ports:
      - "8080:80"
    depends_on:
      - slave_server

  slave_server:
    build: ./slave
    ports:
      - "8081:80"
